<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>

    <Author>Faruk Awofeso</Author>
    <Company>Faruk Awofeso</Company>
    <Description>ASP.NET Core middleware for TierGate — tiered rate limiting and quota enforcement.</Description>
    <PackageProjectUrl>https://github.com/FarukA1/TierGate</PackageProjectUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <PackageTags>rate limiting, quota, throttling, tiers, saas, aspnetcore</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TierGate.Core\TierGate.Core.csproj" />
  </ItemGroup>

</Project>
